Repository boostcamp-2020/IssueTracker-13, pull requests merged in 2020-11, with the labels that each got.

#66 [#65] Sequelize 모델, Migration, Seeder 정의
  backend/.sequelizerc
  backend/config/config.js
  backend/config/config.json
  backend/migrations/20201102152307-create-user.js
  backend/migrations/20201102152322-create-issue.js
  backend/migrations/20201102152331-create-comment.js
  backend/migrations/20201102152341-create-label.js
  backend/migrations/20201102152351-create-milestone.js
  backend/migrations/20201102160147-add-associations-oneToMany.js
  backend/migrations/20201102161947-add-associations-manyToMany.js
  backend/models/comment.js
  backend/models/issue.js
  backend/models/label.js
  backend/models/milestone.js
  backend/models/user.js
  backend/package.json
  backend/seeders/20201102174302-sample-user.js
  backend/seeders/20201102174327-sample-label.js
  backend/seeders/20201102174333-sample-milestone.js
  backend/seeders/20201102174339-sample-issue.js
  backend/seeders/20201102174345-sample-comment.js
  backend/seeders/20201102182107-sample-assignee.js
  backend/seeders/20201102182116-sample-issueLabel.js
Labels: BE

#64 [iOS] CollectionView Swipe Action 구현
  iOS/IssueTracker/IssueTracker/BaseCollectionViewController.swift
  iOS/IssueTracker/IssueTracker/Scenes/IssueList/IssueListInteractor.swift
  iOS/IssueTracker/IssueTracker/Scenes/IssueList/IssueListViewController.swift
  iOS/IssueTracker/IssueTracker/Scenes/IssueList/Models/Issue.swift
  iOS/IssueTracker/IssueTracker/Scenes/IssueList/Models/IssueDataSource.swift
Labels: iOS

#63 SelectAll, dynamic NavigationTitle, 이슈 추가 버튼 구현
  iOS/IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  iOS/IssueTracker/IssueTracker/Base.lproj/Main.storyboard
  iOS/IssueTracker/IssueTracker/Scenes/IssueList/IssueListViewController.swift
  iOS/IssueTracker/IssueTracker/Scenes/IssueList/Views/FloatingButton.swift
Labels: iOS

#67 [iOS] Floating Button, Toolbar, Tab bar 레이아웃 버그 수정
  iOS/IssueTracker/IssueTracker/Base.lproj/Main.storyboard
  iOS/IssueTracker/IssueTracker/Scenes/IssueList/IssueListViewController.swift
Labels: iOS

#68 [#github action] github action을 사용하기위해 관련파일 재설정
  .github/workflows/frontend.yml
  backend/package-lock.json
  backend/package.json
  frontend/.eslintrc.js
  frontend/package.json
  frontend/webpack.config.js
Labels: infra

#86 Milestone Get API 구현
  backend/app.js
  backend/src/db/models/index.js
  backend/src/db/models/user.js
  backend/src/routes/index.js
  backend/src/routes/milestones.js
  backend/src/services/milestoneService.js
Labels: BE, bug

#88 [#75, #79] Issues, Milestones CRUD 구현
  backend/src/db/models/issue.js
  backend/src/routes/issues.js
  backend/src/routes/milestones.js
  backend/src/services/issueService.js
  backend/src/services/milestoneService.js
Labels: BE, bug

#91 iOS Filter Issue View Controller 까지 구현
  iOS/IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  iOS/IssueTracker/IssueTracker/Base.lproj/Main.storyboard
  iOS/IssueTracker/IssueTracker/Scenes/FilterIssue/FilterIssueInteractor.swift
  iOS/IssueTracker/IssueTracker/Scenes/FilterIssue/FilterIssueViewController.swift
  iOS/IssueTracker/IssueTracker/Scenes/IssueList/IssueListInteractor.swift
  iOS/IssueTracker/IssueTracker/Scenes/IssueList/IssueListViewController.swift
  iOS/IssueTracker/IssueTracker/Scenes/IssueList/Models/IssueDataSource.swift
  iOS/IssueTracker/IssueTracker/Scenes/IssueList/Views/IssueCollectionViewCell.swift
Labels: iOS

#90 [#77] Labels API 기본 CRUD 구현
  backend/src/routes/labels.js
  backend/src/services/labelService.js
Labels: BE

#92 Comment API CRU 구현
  backend/src/routes/comments.js
  backend/src/routes/index.js
  backend/src/services/commentService.js
Labels: BE

#93 [#72] GitHub Oauth API 구현
  backend/package-lock.json
  backend/package.json
  backend/src/db/migrations/20201102160147-add-associations-oneToMany.js
  backend/src/db/models/user.js
  backend/src/routes/auth.js
  backend/src/services/passportServices.js
Labels: BE

#95 Filter화면 및 UserList화면 구현
  iOS/IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  iOS/IssueTracker/IssueTracker/Base.lproj/Main.storyboard
  iOS/IssueTracker/IssueTracker/Scenes/FilterIssue/FilterIssueInteractor.swift
  iOS/IssueTracker/IssueTracker/Scenes/FilterIssue/FilterIssueViewController.swift
  iOS/IssueTracker/IssueTracker/Scenes/FilterIssue/FilterLabelListViewController.swift
  iOS/IssueTracker/IssueTracker/Scenes/FilterIssue/FilterMilestoneListViewController.swift
  iOS/IssueTracker/IssueTracker/Scenes/FilterIssue/FilterWorker.swift
  iOS/IssueTracker/IssueTracker/Scenes/FilterIssue/UserListInteractor.swift
  iOS/IssueTracker/IssueTracker/Scenes/FilterIssue/UserListViewController.swift
  iOS/IssueTracker/IssueTracker/Scenes/IssueList/Models/Issue.swift
  iOS/IssueTracker/IssueTracker/Scenes/IssueList/Models/User.swift
Labels: iOS

#97 [iOS] feat: Filter Label List View Controller 구현
  iOS/IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  iOS/IssueTracker/IssueTracker/Base.lproj/Main.storyboard
  iOS/IssueTracker/IssueTracker/Scenes/FilterIssue/FilterIssueInteractor.swift
  iOS/IssueTracker/IssueTracker/Scenes/FilterIssue/FilterIssueViewController.swift
  iOS/IssueTracker/IssueTracker/Scenes/FilterIssue/FilterLabelListViewController.swift
  iOS/IssueTracker/IssueTracker/Scenes/FilterIssue/FitlterLabelInteractor.swift
  iOS/IssueTracker/IssueTracker/Scenes/FilterIssue/UserListViewController.swift
  iOS/IssueTracker/IssueTracker/Scenes/IssueList/Models/Label.swift
Labels: iOS

#96 Feature/filter milestone
  iOS/IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  iOS/IssueTracker/IssueTracker/Base.lproj/Main.storyboard
  iOS/IssueTracker/IssueTracker/Scenes/FilterIssue/FilterIssueInteractor.swift
  iOS/IssueTracker/IssueTracker/Scenes/FilterIssue/FilterIssueViewController.swift
  iOS/IssueTracker/IssueTracker/Scenes/FilterIssue/FilterMilestoneListInteractor.swift
  iOS/IssueTracker/IssueTracker/Scenes/FilterIssue/FilterMilestoneListViewController.swift
  iOS/IssueTracker/IssueTracker/Scenes/FilterIssue/FilterUserListInteractor.swift
  iOS/IssueTracker/IssueTracker/Scenes/FilterIssue/FilterUserListViewController.swift
Labels: iOS

#98 feat: 로그인 화면 View 구현
  iOS/IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  iOS/IssueTracker/IssueTracker/Base.lproj/Main.storyboard
  iOS/IssueTracker/IssueTracker/SceneDelegate.swift
  iOS/IssueTracker/IssueTracker/Scenes/IssueList/IssueListViewController.swift
  iOS/IssueTracker/IssueTracker/Scenes/SignIn/SignInInteractor.swift
  iOS/IssueTracker/IssueTracker/Scenes/SignIn/SignInViewController.swift
Labels: iOS

#105 Sign in with Apple 구현중
  iOS/IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  iOS/IssueTracker/IssueTracker/Base.lproj/Main.storyboard
  iOS/IssueTracker/IssueTracker/IssueTracker.entitlements
  iOS/IssueTracker/IssueTracker/Scenes/SignIn/SignInInteractor.swift
  iOS/IssueTracker/IssueTracker/Scenes/SignIn/SignInViewController.swift
Labels: iOS

#107 컴포넌트를 함수선언식으로 변경
  frontend/src/components/IssueList.jsx
  frontend/src/components/IssueListCheckBox.jsx
  frontend/src/components/IssueListItem.jsx
  frontend/src/components/IssueListNav.jsx
  frontend/src/components/IssueListNavButton.jsx
  frontend/src/components/NewIssueButton.jsx
  frontend/src/components/PropertyButton.jsx
  frontend/src/components/SearchBar.jsx
  frontend/src/components/SearchInput.jsx
  frontend/src/pages/IssueListPage.jsx
  frontend/src/pages/LabelsPage.jsx
  frontend/src/pages/MilestonesPage.jsx
  frontend/src/pages/NewIssuePage.jsx
Labels: FE

#109 IssueListPage Styling 작업
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.js
  frontend/src/components/Header.jsx
  frontend/src/components/IssueListCheckBox.jsx
  frontend/src/components/IssueListItem.jsx
  frontend/src/components/IssueListNav.jsx
  frontend/src/components/IssueListNavButton.jsx
  frontend/src/components/NewIssueButton.jsx
  frontend/src/components/PropertyButton.jsx
  frontend/src/components/SearchBar.jsx
  frontend/src/components/SearchInput.jsx
  frontend/src/index.html
  frontend/src/pages/IssueListPage.jsx
Labels: FE

#111 PR review 반영
  frontend/src/components/Header.jsx
  frontend/src/components/IssueListItem.jsx
  frontend/src/components/IssueListNav.jsx
  frontend/src/components/NewIssueButton.jsx
  frontend/src/components/PropertyButton.jsx
  frontend/src/components/SearchBar.jsx
Labels: FE

#108 user의 routes,services정의 #76
  backend/src/routes/users.js
  backend/src/services/userService.js
  package-lock.json
Labels: BE

#114 Feature/alert view controller
  iOS/IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  iOS/IssueTracker/IssueTracker/Base.lproj/Main.storyboard
  iOS/IssueTracker/IssueTracker/Scenes/Alert/AlertDisplayable.swift
  iOS/IssueTracker/IssueTracker/Scenes/Alert/BaseAlertViewController.swift
  iOS/IssueTracker/IssueTracker/Scenes/Alert/CustomAlertView.swift
  iOS/IssueTracker/IssueTracker/Scenes/Alert/CustomAlertView.xib
  iOS/IssueTracker/IssueTracker/Scenes/Alert/LabelAlertViewController.swift
  iOS/IssueTracker/IssueTracker/Scenes/Alert/MilestoneAlertViewController.swift
  iOS/IssueTracker/IssueTracker/Scenes/IssueList/Models/Label.swift
  iOS/IssueTracker/IssueTracker/Scenes/IssueList/Models/Milestone.swift
Labels: iOS

#117 Milestone GET API 버그 수정
  backend/src/services/milestoneService.js
Labels: BE, bug

#118 fix: 탭바 아이템 수정 및 필터 선택 UX 수정
  iOS/IssueTracker/IssueTracker/Base.lproj/Main.storyboard
  iOS/IssueTracker/IssueTracker/Scenes/FilterIssue/FilterIssueInteractor.swift
  iOS/IssueTracker/IssueTracker/Scenes/FilterIssue/FilterIssueViewController.swift
  iOS/IssueTracker/IssueTracker/Scenes/FilterIssue/FilterMilestoneListViewController.swift
  iOS/IssueTracker/IssueTracker/Scenes/FilterIssue/FilterUserListViewController.swift
Labels: iOS

#121 [#개발환경] Prettier 적용
  backend/.eslintrc.js
  backend/.prettierignore
  backend/.prettierrc.json
  backend/.vscode/settings.json
  backend/app.js
  backend/package-lock.json
  backend/package.json
  backend/src/db/config/config.js
  backend/src/db/migrations/20201102160147-add-associations-oneToMany.js
  backend/src/db/migrations/20201102161947-add-associations-manyToMany.js
  backend/src/db/models/comment.js
  backend/src/db/models/index.js
  backend/src/db/models/issue.js
  backend/src/db/models/label.js
  backend/src/db/models/milestone.js
  backend/src/db/models/user.js
  backend/src/db/seeders/20201102174302-sample-user.js
  backend/src/db/seeders/20201102174327-sample-label.js
  backend/src/db/seeders/20201102174333-sample-milestone.js
  backend/src/db/seeders/20201102174339-sample-issue.js
  backend/src/db/seeders/20201102174345-sample-comment.js
  backend/src/db/seeders/20201102182107-sample-assignee.js
  backend/src/db/seeders/20201102182116-sample-issueLabel.js
  backend/src/db/utils/initDatabase.js
  backend/src/routes/auth.js
  backend/src/routes/issues.js
  backend/src/routes/labels.js
  backend/src/routes/milestones.js
  backend/src/services/commentService.js
  backend/src/services/issueService.js
  backend/src/services/labelService.js
  backend/src/services/milestoneService.js
  backend/src/services/passportServices.js
  backend/src/services/userService.js
  backend/tests/integrations/labels.test.js
Labels: BE

#120 [#Chore] GitHub PR 템플릿 파일 추가
  .github/pull_request_template.md
Labels: documentation

#122 [#배포] 자동배포 기능 추가
  .github/workflows/deploy-dev.yml
  .github/workflows/deploy-prod.yml
  backend/app.js
  ecosystem.config.js
  frontend/webpack.config.js
  package-lock.json
  package.json
Labels: BE, infra

#125 [#배포] PM2 관련 스크립트 오류 수정
  .github/workflows/deploy-dev.yml
  .github/workflows/deploy-prod.yml
Labels: bug, infra

#123 Alert 사용시 사용자 UX 개선
  iOS/IssueTracker/.swiftlint.yml
  iOS/IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  iOS/IssueTracker/IssueTracker/Base.lproj/Main.storyboard
  iOS/IssueTracker/IssueTracker/BaseCollectionViewController.swift
  iOS/IssueTracker/IssueTracker/Extensions/Date+String.swift
  iOS/IssueTracker/IssueTracker/Extensions/String+Date.swift
  iOS/IssueTracker/IssueTracker/Extensions/UIButton+UIColor.swift
  iOS/IssueTracker/IssueTracker/Extensions/UIColor+hexString.swift
  iOS/IssueTracker/IssueTracker/Scenes/Alert/BaseAlertViewController.swift
  iOS/IssueTracker/IssueTracker/Scenes/Alert/CustomAlertView.swift
  iOS/IssueTracker/IssueTracker/Scenes/Alert/CustomAlertView.xib
  iOS/IssueTracker/IssueTracker/Scenes/Alert/LabelAlertInteractor.swift
  iOS/IssueTracker/IssueTracker/Scenes/Alert/LabelAlertViewController.swift
  iOS/IssueTracker/IssueTracker/Scenes/Alert/MilestoneAlertViewController.swift
  iOS/IssueTracker/IssueTracker/Scenes/FilterIssue/FilterLabelListViewController.swift
  iOS/IssueTracker/IssueTracker/Scenes/FilterIssue/FilterWorker.swift
  iOS/IssueTracker/IssueTracker/Scenes/IssueList/IssueWorker.swift
  iOS/IssueTracker/IssueTracker/Scenes/IssueList/Models/Milestone.swift
  iOS/IssueTracker/IssueTracker/Scenes/IssueList/Views/IssueCollectionViewCell.swift
  iOS/IssueTracker/IssueTracker/Scenes/IssueList/Views/LabelBadgeLabel.swift
  iOS/IssueTracker/IssueTracker/Scenes/LabelList/LabelCollectionViewCell.swift
  iOS/IssueTracker/IssueTracker/Scenes/LabelList/LabelListViewController.swift
  iOS/IssueTracker/IssueTracker/Scenes/LabelList/LabelListWorker.swift
  iOS/IssueTracker/IssueTracker/Scenes/MilestoneList/MilestoneCollectionViewCell.swift
  iOS/IssueTracker/IssueTracker/Scenes/MilestoneList/MilestoneDataSource.swift
  iOS/IssueTracker/IssueTracker/Scenes/MilestoneList/MilestoneListInteractor.swift
  iOS/IssueTracker/IssueTracker/Scenes/MilestoneList/MilestoneListViewController.swift
  iOS/IssueTracker/IssueTracker/Scenes/MilestoneList/MilestoneListWorker.swift
Labels: iOS

#124 API 연동
  frontend/package-lock.json
  frontend/package.json
  frontend/src/apis/issuesAPI.js
  frontend/src/components/IssueList.jsx
  frontend/src/components/IssueListItem.jsx
Labels: FE

#127 [iOS] feat: API 제네릭으로 변경
  iOS/IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  iOS/IssueTracker/IssueTracker/API.swift
  iOS/IssueTracker/IssueTracker/Base.lproj/Main.storyboard
  iOS/IssueTracker/IssueTracker/EndPoint.swift
  iOS/IssueTracker/IssueTracker/Models/Issue.swift
  iOS/IssueTracker/IssueTracker/Models/Label.swift
  iOS/IssueTracker/IssueTracker/Models/Milestone.swift
  iOS/IssueTracker/IssueTracker/Models/User.swift
  iOS/IssueTracker/IssueTracker/Response.swift
  iOS/IssueTracker/IssueTracker/Scenes/IssueList/IssueDataSource.swift
  iOS/IssueTracker/IssueTracker/Scenes/LabelList/LabelListWorker.swift
  iOS/IssueTracker/IssueTracker/Scenes/MilestoneList/MilestoneCollectionViewCell.swift
  iOS/IssueTracker/IssueTracker/Scenes/MilestoneList/MilestoneDataSource.swift
  iOS/IssueTracker/IssueTracker/Scenes/MilestoneList/MilestoneListInteractor.swift
  iOS/IssueTracker/IssueTracker/Scenes/MilestoneList/MilestoneListWorker.swift
Labels: iOS

#130 feat: 이슈 수정 / 작성 뷰 컨트롤러 연결
  iOS/IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  iOS/IssueTracker/IssueTracker/Base.lproj/Main.storyboard
  iOS/IssueTracker/IssueTracker/Scenes/IssueDetail/IssueDetailViewController.swift
  iOS/IssueTracker/IssueTracker/Scenes/IssueEdit/IssueEditViewController.swift
  iOS/IssueTracker/IssueTracker/Scenes/IssueList/IssueListViewController.swift
Labels: iOS

#128 [#수정사항] Comments API에 User 정보 추가
  backend/src/services/commentService.js
Labels: BE

#131 Pull to refresh 구현
  iOS/IssueTracker/IssueTracker/BaseCollectionViewController.swift
  iOS/IssueTracker/IssueTracker/Scenes/IssueList/IssueListViewController.swift
  iOS/IssueTracker/IssueTracker/Scenes/LabelList/LabelListViewController.swift
  iOS/IssueTracker/IssueTracker/Scenes/MilestoneList/MilestoneListViewController.swift
Labels: iOS

#156 라벨 목록 네트워킹 연동
  iOS/IssueTracker/IssueTracker/Models/Label.swift
  iOS/IssueTracker/IssueTracker/Scenes/Alert/LabelAlertInteractor.swift
  iOS/IssueTracker/IssueTracker/Scenes/Alert/LabelAlertViewController.swift
  iOS/IssueTracker/IssueTracker/Scenes/LabelList/LabelDataSource.swift
  iOS/IssueTracker/IssueTracker/Scenes/LabelList/LabelListInteractor.swift
  iOS/IssueTracker/IssueTracker/Scenes/LabelList/LabelListViewController.swift
Labels: iOS

#157 fix: 라벨 제목 길때 예외처리
  iOS/IssueTracker/IssueTracker/Base.lproj/Main.storyboard
Labels: iOS

#158 이슈추가화면 UX 개선 및 markdown 렌더링 구현
  iOS/IssueTracker/IssueTracker/Base.lproj/Main.storyboard
  iOS/IssueTracker/IssueTracker/Scenes/IssueEdit/IssueEditViewController.swift
  iOS/IssueTracker/Podfile
  iOS/IssueTracker/Podfile.lock
Labels: iOS

#160 [iOS] feat: Filter 기능 구현
  iOS/IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  iOS/IssueTracker/IssueTracker/API.swift
  iOS/IssueTracker/IssueTracker/Base.lproj/Main.storyboard
  iOS/IssueTracker/IssueTracker/Models/Filter.swift
  iOS/IssueTracker/IssueTracker/Models/Issue.swift
  iOS/IssueTracker/IssueTracker/Models/Label.swift
  iOS/IssueTracker/IssueTracker/Models/Milestone.swift
  iOS/IssueTracker/IssueTracker/Models/User.swift
  iOS/IssueTracker/IssueTracker/Scenes/Alert/MilestoneAlertViewController.swift
  iOS/IssueTracker/IssueTracker/Scenes/FilterIssue/FilterIssueInteractor.swift
  iOS/IssueTracker/IssueTracker/Scenes/FilterIssue/FilterIssueViewController.swift
  iOS/IssueTracker/IssueTracker/Scenes/FilterIssue/FilterUserListViewController.swift
  iOS/IssueTracker/IssueTracker/Scenes/FilterIssue/FilterWorker.swift
  iOS/IssueTracker/IssueTracker/Scenes/FilterIssue/FitlterLabelInteractor.swift
  iOS/IssueTracker/IssueTracker/Scenes/IssueList/IssueListInteractor.swift
  iOS/IssueTracker/IssueTracker/Scenes/IssueList/IssueListViewController.swift
  iOS/IssueTracker/IssueTracker/Scenes/IssueList/IssueWorker.swift
  iOS/IssueTracker/IssueTracker/Scenes/IssueList/Views/IssueCollectionViewCell.swift
  iOS/IssueTracker/IssueTracker/Scenes/MilestoneList/MilestoneCollectionViewCell.swift
Labels: iOS

#159 [#132] Users API 반환값에서 password, authType 삭제
  backend/src/services/userService.js
Labels: BE, bug

#129 필터링 기능 구현
  backend/src/routes/milestones.js
  backend/src/services/milestoneService.js
  frontend/src/apis/issuesAPI.js
  frontend/src/apis/labelsAPI.js
  frontend/src/apis/milestonesAPI.js
  frontend/src/apis/usersAPI.js
  frontend/src/assets/filter.js
  frontend/src/components/FilterModal.jsx
  frontend/src/components/IssueList.jsx
  frontend/src/components/IssueListNav.jsx
  frontend/src/components/IssueListNavButton.jsx
  frontend/src/components/SearchInput.jsx
  frontend/src/mocks/issues.json
  frontend/src/mocks/labels.json
  frontend/src/mocks/milestones.json
  frontend/src/pages/IssueListPage.jsx
Labels: FE

#126 [#74] Feature/jwt 완성
  .github/workflows/backend.yml
  backend/package-lock.json
  backend/package.json
  backend/src/db/migrations/20201102152307-create-user.js
  backend/src/db/models/user.js
  backend/src/db/seeders/20201102174302-sample-user.js
  backend/src/routes/auth.js
  backend/src/routes/index.js
  backend/src/services/authService.js
Labels: BE

#161 [#139, #141, #144, #148] Milestones 페이지 컴포넌트 구조 구현
  backend/src/db/migrations/20201102152351-create-milestone.js
  backend/src/db/models/milestone.js
  backend/src/db/seeders/20201102174333-sample-milestone.js
  backend/src/services/milestoneService.js
  frontend/src/apis/milestonesAPI.js
  frontend/src/components/LabelMilestoneHeader.jsx
  frontend/src/components/MilestoneList.jsx
  frontend/src/components/MilestoneListItem.jsx
  frontend/src/components/MilestoneListNav.jsx
  frontend/src/components/NewButton.jsx
  frontend/src/components/OpenClosedButton.jsx
  frontend/src/components/PropertyButton.jsx
  frontend/src/pages/MilestonesPage.jsx
Labels: FE

#171 [#Structure] 이슈상세페이지 구조 설정
  frontend/src/components/CommentInput.jsx
  frontend/src/components/CommentList.jsx
  frontend/src/components/IssueDetailHeader.jsx
  frontend/src/components/IssueDetailSidebar.jsx
  frontend/src/pages/IssueDetailPage.jsx
Labels: FE

#172 [iOS] Feat/issue detail
  iOS/IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  iOS/IssueTracker/IssueTracker.xcworkspace/xcshareddata/swiftpm/Package.resolved
  iOS/IssueTracker/IssueTracker/Base.lproj/Main.storyboard
  iOS/IssueTracker/IssueTracker/Scenes/IssueDetail/IssueBottomSheetViewController.swift
  iOS/IssueTracker/IssueTracker/Scenes/IssueDetail/IssueDetailViewController.swift
  iOS/IssueTracker/IssueTracker/Scenes/IssueList/IssueListViewController.swift
Labels: iOS

#173 [#170] 단일 issue GET API 구현
  backend/src/routes/issues.js
  backend/src/services/issueService.js
Labels: BE

#177 [#Fix] iOS 요청에 따라 issues API author에 profile 추가
  backend/src/services/issueService.js
Labels: BE, enhancement

#175 feat: Issue 상세 화면 Bottom Sheet 레이아웃 작업 완료
  iOS/IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  iOS/IssueTracker/IssueTracker/Base.lproj/Main.storyboard
  iOS/IssueTracker/IssueTracker/Scenes/IssueDetail/ButtonWithShadow.swift
  iOS/IssueTracker/IssueTracker/Scenes/IssueDetail/IssueBottomSheetViewController.swift
  iOS/IssueTracker/IssueTracker/Scenes/IssueDetail/IssueDetailViewController.swift
Labels: iOS

#178 Issue 상세 comment 화면 구현/ 화면에 업데이트 안되는 버그 수정 / label stackview 구현
  iOS/IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  iOS/IssueTracker/IssueTracker/Base.lproj/Main.storyboard
  iOS/IssueTracker/IssueTracker/Extensions/UIImageView+Extension.swift
  iOS/IssueTracker/IssueTracker/Models/Comment.swift
  iOS/IssueTracker/IssueTracker/Scenes/IssueDetail/IssueDetailDataSource.swift
  iOS/IssueTracker/IssueTracker/Scenes/IssueDetail/IssueDetailInteractor.swift
  iOS/IssueTracker/IssueTracker/Scenes/IssueDetail/IssueDetailViewController.swift
  iOS/IssueTracker/IssueTracker/Scenes/IssueDetail/IssueDetailWorker.swift
  iOS/IssueTracker/IssueTracker/Scenes/IssueDetail/Views/CommentCollectionReusableView.swift
  iOS/IssueTracker/IssueTracker/Scenes/IssueDetail/Views/CommentCollectionViewCell.swift
  iOS/IssueTracker/IssueTracker/Scenes/IssueList/IssueListViewController.swift
  iOS/IssueTracker/IssueTracker/Scenes/IssueList/Views/IssueCollectionViewCell.swift
  iOS/IssueTracker/IssueTracker/Scenes/LabelList/LabelListInteractor.swift
  iOS/IssueTracker/IssueTracker/Scenes/MilestoneList/MilestoneListInteractor.swift
Labels: iOS

#180 [#134] IssueDetailSidebar 컴포넌트 구현
  backend/src/routes/issues.js
  backend/src/services/issueService.js
  backend/src/services/userService.js
  frontend/src/apis/issuesAPI.js
  frontend/src/components/FilterModal.jsx
  frontend/src/components/IssueDetailSidebar.jsx
  frontend/src/components/SelectSidebar/SelectAssigneesBox.jsx
  frontend/src/components/SelectSidebar/SelectAssigneesContents.jsx
  frontend/src/components/SelectSidebar/SelectBoxHeader.jsx
  frontend/src/components/SelectSidebar/SelectLabelsBox.jsx
  frontend/src/components/SelectSidebar/SelectLabelsContents.jsx
  frontend/src/components/SelectSidebar/SelectMilestoneBox.jsx
  frontend/src/components/SelectSidebar/SelectMilestoneContents.jsx
  frontend/src/components/SelectSidebar/SelectSidebar.jsx
  frontend/src/components/SelectSidebar/SidebarModal.jsx
  frontend/src/pages/IssueDetailPage.jsx
Labels: BE, FE

#176 [#146] IssueDetailHeader, NewIssuePage 컴포넌트 구현
  frontend/src/App.js
  frontend/src/assets/icons.js
  frontend/src/components/FilterModal.jsx
  frontend/src/components/Header.jsx
  frontend/src/components/IssueDetailHeader.jsx
  frontend/src/components/IssueListItem.jsx
  frontend/src/components/LabelMilestoneHeader.jsx
  frontend/src/components/NewIssueButton.jsx
  frontend/src/components/SearchBar.jsx
  frontend/src/index.html
  frontend/src/pages/IssueDetailPage.jsx
  frontend/src/pages/NewIssuePage.jsx
Labels: FE

#183 이슈 추가, 이슈 수정, 댓글 수정 화면 변경 및 구현
  iOS/IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  iOS/IssueTracker/IssueTracker/Base.lproj/Main.storyboard
  iOS/IssueTracker/IssueTracker/Models/Comment.swift
  iOS/IssueTracker/IssueTracker/Scenes/IssueDetail/IssueDetailViewController.swift
  iOS/IssueTracker/IssueTracker/Scenes/IssueDetail/Views/ButtonWithShadow.swift
  iOS/IssueTracker/IssueTracker/Scenes/IssueDetail/Views/EditTitleViewController.swift
  iOS/IssueTracker/IssueTracker/Scenes/IssueEdit/IssueEditViewController.swift
Labels: iOS

#184 Feat/issue detail
  iOS/IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  iOS/IssueTracker/IssueTracker/Base.lproj/Main.storyboard
  iOS/IssueTracker/IssueTracker/Models/Issue.swift
  iOS/IssueTracker/IssueTracker/Scenes/FilterIssue/FilterIssueInteractor.swift
  iOS/IssueTracker/IssueTracker/Scenes/FilterIssue/FilterIssueViewController.swift
  iOS/IssueTracker/IssueTracker/Scenes/FilterIssue/FilterLabelListViewController.swift
  iOS/IssueTracker/IssueTracker/Scenes/FilterIssue/FilterUserListViewController.swift
  iOS/IssueTracker/IssueTracker/Scenes/FilterIssue/FitlterLabelInteractor.swift
  iOS/IssueTracker/IssueTracker/Scenes/IssueDetail/IssueBottomSheetInteractor.swift
  iOS/IssueTracker/IssueTracker/Scenes/IssueDetail/IssueBottomSheetViewController.swift
  iOS/IssueTracker/IssueTracker/Scenes/IssueDetail/IssueDetailViewController.swift
Labels: iOS

#185 [#Fix] Comment POST API에서 author 인식 추가
  backend/src/routes/comments.js
Labels: BE, enhancement

#189 [iOS] 필터 기능 및 수정 기능 업데이트
  iOS/IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  iOS/IssueTracker/IssueTracker/API.swift
  iOS/IssueTracker/IssueTracker/Base.lproj/Main.storyboard
  iOS/IssueTracker/IssueTracker/Models/Filter.swift
  iOS/IssueTracker/IssueTracker/Models/Issue.swift
  iOS/IssueTracker/IssueTracker/Models/User.swift
  iOS/IssueTracker/IssueTracker/Scenes/FilterIssue/FilterIssueInteractor.swift
  iOS/IssueTracker/IssueTracker/Scenes/FilterIssue/FilterIssueViewController.swift
  iOS/IssueTracker/IssueTracker/Scenes/FilterIssue/FilterLabelListViewController.swift
  iOS/IssueTracker/IssueTracker/Scenes/FilterIssue/FilterMilestoneListInteractor.swift
  iOS/IssueTracker/IssueTracker/Scenes/FilterIssue/FilterMilestoneListViewController.swift
  iOS/IssueTracker/IssueTracker/Scenes/FilterIssue/FilterUserListInteractor.swift
  iOS/IssueTracker/IssueTracker/Scenes/FilterIssue/FilterUserListViewController.swift
  iOS/IssueTracker/IssueTracker/Scenes/FilterIssue/FilterWorker.swift
  iOS/IssueTracker/IssueTracker/Scenes/IssueDetail/IssueBottomSheetInteractor.swift
  iOS/IssueTracker/IssueTracker/Scenes/IssueDetail/IssueBottomSheetViewController.swift
  iOS/IssueTracker/IssueTracker/Scenes/IssueDetail/IssueBottomSheetWorker.swift
  iOS/IssueTracker/IssueTracker/Scenes/IssueDetail/IssueDetailViewController.swift
  iOS/IssueTracker/IssueTracker/Scenes/IssueDetail/IssueEditWorker.swift
  iOS/IssueTracker/IssueTracker/Scenes/IssueList/IssueListInteractor.swift
  iOS/IssueTracker/IssueTracker/Scenes/IssueList/IssueListViewController.swift
  iOS/IssueTracker/IssueTracker/Scenes/IssueList/Views/IssueCollectionViewCell.swift
Labels: iOS

#191 [#Fix] 이슈 추가하면서 처음 코멘트 입력기능 추가
  backend/src/routes/issues.js
  backend/src/services/issueService.js
Labels: BE

#192 fix: conflict 해결
  iOS/IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  iOS/IssueTracker/IssueTracker/Base.lproj/Main.storyboard
  iOS/IssueTracker/IssueTracker/Scenes/IssueDetail/IssueDetailInteractor.swift
Labels: iOS

#181 [#162, #164] 마일스톤 페이지 이벤트 추가
  backend/src/routes/milestones.js
  frontend/src/apis/milestonesAPI.js
  frontend/src/components/MilestoneList.jsx
  frontend/src/components/MilestoneListItem.jsx
  frontend/src/components/MilestoneListNav.jsx
  frontend/src/components/OpenClosedButton.jsx
  frontend/src/pages/MilestonesPage.jsx
Labels: BE, FE

#188 [#153] Local 로그인, 회원가입 기능 구현
  backend/src/routes/auth.js
  backend/src/services/authService.js
  frontend/src/App.js
  frontend/src/apis/authAPI.js
  frontend/src/apis/issuesAPI.js
  frontend/src/apis/labelsAPI.js
  frontend/src/apis/milestonesAPI.js
  frontend/src/apis/usersAPI.js
  frontend/src/components/IssueDetailHeader.jsx
  frontend/src/pages/LoginPage.jsx
Labels: BE, FE

#195 [#150, #147, #145, #142] 레이블 리스트 페이지 컴포넌트 구현
  frontend/src/components/LabelList.jsx
  frontend/src/components/LabelListItem.jsx
  frontend/src/components/LabelListNav.jsx
  frontend/src/components/LabelMilestoneHeader.jsx
  frontend/src/pages/LabelsPage.jsx
  frontend/src/pages/MilestonesPage.jsx
Labels: FE

#194 feat: 이슈 클로즈 기능 추가
  iOS/IssueTracker/IssueTracker/API.swift
  iOS/IssueTracker/IssueTracker/Base.lproj/Main.storyboard
  iOS/IssueTracker/IssueTracker/Scenes/IssueDetail/IssueBottomSheetViewController.swift
  iOS/IssueTracker/IssueTracker/Scenes/IssueList/IssueListInteractor.swift
  iOS/IssueTracker/IssueTracker/Scenes/SignIn/SignInViewController.swift
Labels: iOS

#196 feat: 이슈 추가 기능 구현
  iOS/IssueTracker/IssueTracker/Base.lproj/Main.storyboard
  iOS/IssueTracker/IssueTracker/Models/Issue.swift
  iOS/IssueTracker/IssueTracker/Scenes/IssueEdit/IssueEditViewController.swift
  iOS/IssueTracker/IssueTracker/Scenes/IssueList/IssueListInteractor.swift
  iOS/IssueTracker/IssueTracker/Scenes/IssueList/IssueListViewController.swift
Labels: iOS

#204 [#200, #203] Sidebar에서 레이블 짤리는 버그 해결
  frontend/src/components/CommentInput.jsx
  frontend/src/components/SelectSidebar/SelectLabelsContents.jsx
Labels: bug

#206 [#202] fix: 드롭다운 modal이 상위 컴포넌트에 붙어다니도록 변경
  frontend/src/components/FilterModal.jsx
  frontend/src/components/Header.jsx
  frontend/src/components/SelectSidebar/SidebarModal.jsx
Labels: bug

#205 [#198, #209] NewIssue 페이지, 이슈목록 페이지에서 사용자 정보 사용하지 않는 문제
  frontend/src/apis/authAPI.js
  frontend/src/assets/filter.js
  frontend/src/components/SearchInput.jsx
  frontend/src/pages/NewIssuePage.jsx
Labels: bug

#210 [#201, #199] 로그인 관련 버그 수정
  backend/src/routes/auth.js
  backend/src/routes/issues.js
  backend/src/services/authService.js
  frontend/src/apis/authAPI.js
  frontend/src/pages/LoginPage.jsx
Labels: bug
